# Grands super user permissions
sudo: required

# travis ci installs docker into travis container
services:
  - docker
# before tests are ran build docker image
before_install:
  - docker build -t dvontrec/docker-react -f Dockerfile.dev .

# commands used to run tests
script:
  - docker run dvontrec/docker-react npm run test -- --coverage

# Steps to deploy to AWS
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-092753704309'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
